### ISSUE TITLE
이력서 list 페이지 프론트엔드 html, css 작업

### ISSUE THREAD

**Issue by yousunning** [kosmo138/resumate#34]
### 2024-03-21
-  Tailwind CSS를 설치하고 프로젝트에 통합 해야함 
- (tailwind css 설치 후에 shadcn ui 사용)
- React Hook 학습

**Comment by suyons** [comment]
## 240322 문제 진단 및 조치 내용
1. 자바스크립트 문법에 대한 숙지가 부족하여 함수 (람다식), 기본 자료형 (number, string), 객체 (object, array, function)의 개념을 정리함.
2. '복사하기' 및 '이력서 추가' 버튼에 대한 기능 구현을 자바스크립트 객체 수정을 통해 프론트엔드
 화면으로만 진행하고 있었음을 확인하여, 백엔드 REST API에 요청 및 DB CRUD하는 원리를 설명함.
3. 백엔드 REST API 구현 이전까지 자바스크립트의 AJAX 관련 코드 작성은 보류하고
 먼저 HTML+CSS를 이용한 View 구현부터 진행하도록 안내함.
4. 이후 Promise 및 DOM의 개념을 학습하여 `fetch()`, `document.querySelectorAll()` 함수를 사용하여
AJAX 요청 및 응답 JSON을 파싱하여 DOM에 표현할 수 있도록 준비할 것을 요청함.

**Comment by yousunning** [comment]
2024-03-26
- 이력서 목록 페이지 텍스트박스 수정
- 카드 안 input박스 컴포넌트 링크 수정
- DropDown 버튼에 따른 이벤트 생성
- React (Custom Hooks) 학습
