### ISSUE TITLE
자기소개서 edit 페이지 프론트엔드 html, css 작업

### ISSUE THREAD

**Issue by WGCAT** [kosmo138/resumate#38]
1. 사용된 기술조사
2. 테스트코드 작성

**Comment by suyons** [comment]
Close #38

https://github.com/kosmo138/resumate/commit/89094355aa666eebf17a415a14a0ff2cfb7e761d

HTML, CSS 뷰 작성 종료 이후 Javascript를 이용한 비즈니스 로직 작성 중
