### ISSUE TITLE
RestAPI와 resume/[id] 페이지 연결

### ISSUE THREAD

**Issue by mogri89** [kosmo138/resumate#48]
1. 저장버튼에 /resume Patch 요청 예시 코드 추가
2. resume/id 페이지에 /resume/[id] GET 요청으로 저장 자료 불러오는 테스트 코드 추가
3. 2번에 해당하는 더미 데이터 활용하여 수정페이지 초기 값 로드해보기
4. bearer 토큰 활용 방안 학습

**Comment by suyons** [comment]
## Related Commit
https://github.com/kosmo138/resumate/commit/9b1bd941f73f99b9cd5f17ce6d718119c7d0a533

## Changelog
1. Pages Router에서 사용되는 usePathname 대신 App Router에서 사용되는 형식으로 변경
참고: [Dynamic Routes](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes)
2. useEffect() - fetch() - setState() 함수 문제 해결
3. Mock data 코드 삭제
4. ResumeHead 및 ResumeBody 타입 정의
