### ISSUE TITLE
프론트엔드 UI 목업 디자인

### ISSUE THREAD

**Issue by suyons** [kosmo138/resumate#8]
- [x] 랜딩 페이지 목업 디자인
- [x] 이력서 목록 페이지 목업 디자인
- [x] 이력서 편집 페이지 목업 디자인
- [x] 자기소개서 생성 페이지 목업 디자인

**Comment by suyons** [comment]
## shadcn/ui 컴포넌트 라이브러리 소개
**MUI 대비 장점**
- MUI: node_modules 폴더에 일괄 다운로드되어 해당 컴포넌트에 대한 주도권을 사용자가 갖지 않음.
- shadcn: 프로젝트 내 components 폴더에 개별로 컴포넌트가 추가되며, 사용자가 주도권을 가짐

**Docs**
- https://ui.shadcn.com/docs/installation/next

**Examples**
- https://ui.shadcn.com/examples/mail
- https://github.com/shadcn-ui/ui/tree/main/apps/www/app/examples

**Comment by suyons** [comment]
## 현재 발생하는 런타임 오류 분석
### 오류 내용
```
 ✓ Compiled in 232ms (520 modules)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check your code at Header.tsx:13.

⚠ Fast Refresh had to perform a full reload due to a runtime error.
Internal error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
### 오류 해석
Header.tsx:13에 string, class, function이 와야 하는데 왜 object가 옵니까?

### 해결 방안 탐색
다음의 블로그 글에서도 SVG 파일을 import하면서 문제가 발생했다는 기록을 확인
https://cheolsker.tistory.com/81

아직 문제점 파악이 제대로 되지 않아 추가 탐색 및 학습 진행 중

**Comment by suyons** [comment]
## 240311 진행 상황
1. 랜딩 페이지 목업 디자인 완료
   * 기존의 작업 파일 개선: 12 column grid 적용, 요소명을 HTML 시맨틱 태그로 변경
2. 이력서 목록 페이지 목업 디자인 완료
3. 이력서 편집 페이지: header, footer, main 등 큰 틀은 @suyons 가 작업 후 main 태그 내부의 세부 페이지는 @yousunning 이 진행 중
4. 자기소개서 생성 페이지 목업 디자인 이후 랜딩 페이지 코드로 구현 진행할 예정

**Comment by yousunning** [comment]
### 240311 진행 상황
1. editor - 이력서 정보 입력란 화면 정의 완료
2. 균일한 요소간 거리 보완필요함.
3. 태그정보 정리예정.

**Comment by yousunning** [comment]
### 240312 진행 상황
자기소개서 세부 페이지 목업 디자인 완료.
기존의 작업 파일 개선: Auto layout 보완 완료. 요소명을 HTML 시맨틱 태그로 변경.

**Comment by suyons** [comment]
# 240314 공지
## 오늘 오후부터 할 일
1. 전체 인원이 한 자리에 모여 A4 용지에 프론트엔드 UI 모형을 그릴 것입니다.
2. 이후, 다이어그램 설계까지도 A4 용지에 그리며 진행하려 합니다.

## 필요 지식 선행 학습
작업을 진행하기 전에 다음 블로그 글을 읽어 주시기 바랍니다.
한 번에 이해가 되지 않을 수 있습니다. 저도 그랬습니다.
작업하면서 막히는 부분은 제가 설명해 드릴 예정이므로 걱정하지 않으셔도 됩니다.

### UML과 다이어그램의 개념
https://lxxyeon.tistory.com/87

### Usecase diagram (쉬움)
https://m.blog.naver.com/if_you-/221001892737

### Entity-Relationship diagram (보통)
https://wonit.tistory.com/215

### Class diagram (어려움)
https://velog.io/@khyunjiee/UML-Class-Diagram

클래스 다이어그램의 작성은 당장 클래스를 어떻게 정의할지 감이 잡히지 않아 난이도가 높을 것으로 예상됩니다.
이 부분은 제가 프로토타입을 작성한 이후 구현 단계의 초입에서 진행하셔도 괜찮을 것이라 생각합니다.

**Comment by yousunning** [comment]
### 2024-03-15 프론트엔드 UI 목업 디자인 현황
#### /resume/list
- 이력서 관리 페이지 수정 완료 
- ( 자기소개서 작성 버튼 추가 및 관리 설정 아이콘 추가, 복제 박스 예시로 추가)
#### /letter/list
- 자기소개서 관리 페이지 추가
-  (이력서 관리에서 자기소개서 작성 버튼 클릭 -> 자기소개서 생성 페이지 이동-> 저장 시에 자기소개서 관리 페이지에 저장됨.)
- (이력서 박스 클릭 -> 이력서 수정 및 확인 가능)
#### /letter/edit
- 자기소개서 생성 페이지 추가
-  (이력서 관리에서 자기소개서 작성 버튼 클릭 시 이 페이지로 이동)

-> 간단 자기소개서를 참고하여 자기소개서 생성해 줄 modal창 생성
-> 답변 버튼 클릭 시  자기소개서 생성란에 입력됨.
-> 다른 카테고리로 추가 등록 하고 싶을 경우 추가 버튼 사용.
-> 완성 후 저장 버튼 클릭.
#### /recruit
- 채용공고 페이지 추가
- 채공공고를 제목 및 상세검색(지역, 경력, 학력) 으로 워크넷 정보 가져오기
